name: "Validate 'export' branch"
on:
  push:
    branches:
      - export

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        defconfig: ['x86_64', 'i386']
        ipv6: ['with_ipv6', 'without_ipv6']
        mptcp: ['with_mptcp', 'without_mptcp']
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
        with:
          fetch-depth: 100 # we should not have more commits on top of net-next
      - name: "Setup cache for CCache"
        uses: actions/cache@v2
        with:
          path: ${{ github.workspace }}/.ccache
          key: ${{ runner.os }}-build-${{ matrix.defconfig }}-${{ matrix.ipv6 }}-${{ matrix.mptcp }}-${{ github.run_id }}-${{ github.sha }}
          restore-keys: ${{ runner.os }}-build-${{ matrix.defconfig }}-${{ matrix.ipv6 }}-${{ matrix.mptcp }}-
      - name: "Validate export"
        uses: multipath-tcp/mptcp-upstream-validate-export-action@main
        with:
          each_commit: true
          ccache_maxsize: 620M ## 5/2^3=625: 5GB = project limit ; 2^3 = matrix
          defconfig: ${{ matrix.defconfig }}
          ipv6: ${{ matrix.ipv6 }}
          mptcp: ${{ matrix.mptcp }}
          base: bottom
